networks:
- name: bosh
  subnets:
  - azs:
    - ap-northeast-1a
    cloud_properties:
      subnet: subnet-0a829342a79b16704
    dns:
    - 10.0.0.2
    gateway: 10.0.8.1
    range: 10.0.8.0/24
    reserved:
    - 10.0.8.0-10.0.8.128 # reserved for pas-service-network
    static: []
  - azs:
    - ap-northeast-1d
    cloud_properties:
      subnet: subnet-008edf3de6c85b1df
    dns:
    - 10.0.0.2
    gateway: 10.0.9.1
    range: 10.0.9.0/24
    reserved:
    - 10.0.9.0-10.0.9.128  # reserved for pas-service-network
    static: []
  - azs:
    - ap-northeast-1c
    cloud_properties:
      subnet: subnet-046428303898651ff
    dns:
    - 10.0.0.2
    gateway: 10.0.10.1
    range: 10.0.10.0/24
    reserved:
    - 10.0.10.0-10.0.10.128  # reserved for pas-service-network
    static: []
  type: manual
